# PostgreSQL database config

default: &default
  adapter: postgresql
  encoding: unicode
  username: wall-trade
  pool: 5

development:
  <<: *default
  database: wall-trade_development
  #min_messages: notice

test:
  <<: *default
  database: wall-trade_test

production:
  <<: *default
  database: wall-trade_production
  username: wall-trade
  password: <%= ENV['WALL-TRADE_DATABASE_PASSWORD'] %>
